/* test_orgqr_mkl.cpp
 *
 * Validation of cbk_?orgqr_compact against dense LAPACK and against the
 * already-validated cbk_?ormqr_compact, through the genuine MKL Compact
 * pipeline (mkl_?gepack_compact / mkl_?geunpack_compact). The design
 * document's section 7 (cbk_dorgqr_compact_design.md).
 *
 * Suite 1 (vs dense LAPACKE_?orgqr):
 *   A random m x k batch is factored per matrix by LAPACKE_?geqrf, the
 *   reflectors staged into the first k columns of an m x n buffer (garbage
 *   beyond -- those columns must be overwritten), packed, and Q generated by
 *   cbk_?orgqr_compact. Gated: Q elementwise against LAPACKE_?orgqr at
 *   the cross-check tolerance (LAPACKE's blocked accumulation orders the
 *   rounding differently), plus the invariants formed independently --
 *   orthogonality ||Q^T Q - I||_1 <= 100 n eps and reconstruction
 *   ||Q(:,0:k-1) R - A||_1 / ||A||_1 <= 100 m eps. Also checks the
 *   workspace query protocol (work[0] >= 1, and the returned size is what
 *   the call is given -- the value itself is an implementation detail).
 *   Runs in both layouts.
 *
 * Suite 2 (vs cbk_?ormqr_compact on a packed identity, n = k):
 *   The two routes to Q -- orgqr in place over (H, tau), and ormqr('L','N')
 *   applied to a packed identity batch -- must agree elementwise to a small
 *   multiple of eps: same reflectors, same application order, different
 *   structure exploitation. Padded lanes agree too (both produce identity).
 *
 * Build: needs Intel MKL (headers + libmkl_rt); wired up by CMakeLists.txt.
 *
 * Assisted-by: Claude:claude-fable-5
 */

#include "test_mkl_util.hpp" /* compat<T>, mkl<T>, lapack<T> + the shared helpers */

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <limits>
#include <vector>
#include <algorithm>

using namespace cbk::test;

namespace {

/* ---------------- Suite 1: vs dense LAPACKE_?orgqr --------------------- */

template <class T> int suite1(int nm, int m, int n, int k, bool rowmajor = false)
{
    const double eps = std::numeric_limits<T>::epsilon();
    const MKL_COMPACT_PACK fmt = mkl_get_format_compact();
    const int V = mkl<T>::vlen(fmt);
    const MKL_LAYOUT lay = rowmajor ? MKL_ROW_MAJOR : MKL_COL_MAJOR;
    const MKL_INT ld = rowmajor ? n : m;
    /* MKL's pack routines dereference every pointer unconditionally (see
     * .claude/mkl-compact-behavior.md), so keep the extents they see positive
     * even at k = 0; the phantom column is never read by the routine under
     * test. The portable suite needs no such guard. */
    const int kf = std::max(k, 1);

    /* factor a random m x k batch densely; Qd = LAPACKE_?orgqr reference */
    MatrixBatch<T> A0(nm, m, kf), Hk(nm, m, kf), tau(nm, kf, 1), Hn(nm, m, n),
        Qd(nm, m, n), Qc(nm, m, n), S(nm, m, n);
    for (int v = 0; v < nm; ++v) {
        gen_boosted(A0.view(v));
        std::copy(A0[v], A0[v] + A0.stride(), Hk[v]);
        if (k > 0) lapack<T>::geqrf(LAPACK_COL_MAJOR, m, kf, Hk[v], m, tau[v]);

        const auto H = Hn.view(v);
        for (int j = 0; j < n; ++j)
            for (int i = 0; i < m; ++i)
                H(i, j) = (j < k) ? Hk(v, i, j) : frand<T>(); /* garbage cols */

        std::copy(Hn[v], Hn[v] + Hn.stride(), Qd[v]);
        lapack<T>::orgqr(LAPACK_COL_MAJOR, m, n, k, Qd[v], m, tau[v]);

        /* staging in the layout under test (S's storage becomes that layout) */
        copy_matrix(Hn.view(v), S.view(v, rowmajor));
    }

    /* pack the staged batch and the tau batch */
    MKL_INT sz_a = mkl<T>::get_size(m, n, fmt, nm);
    MKL_INT sz_t = mkl<T>::get_size(kf, 1, fmt, nm);
    auto ap_buf = cbk::detail::mkl_alloc_bytes<T>(sz_a);
    auto tp_buf = cbk::detail::mkl_alloc_bytes<T>(sz_t);
    T *ap = ap_buf.get(), *taup = tp_buf.get();
    auto Sp = S.base_ptrs();
    auto Tp = tau.base_ptrs();
    mkl<T>::gepack(lay, m, n, Sp.data(), ld, ap, ld, fmt, nm);
    mkl<T>::gepack(MKL_COL_MAJOR, kf, 1, Tp.data(), kf, taup, kf, fmt, nm);

    int fails = 0;

    /* workspace query (the size is the query's to choose, >= 1), then the
     * call with a buffer of exactly that size */
    MKL_INT info = 99;
    T wq = T(0);
    compat<T>::orgqr(lay, m, n, k, ap, ld, taup, &wq, -1, &info, fmt, nm);
    if (info != 0 || wq < T(1)) {
        ++fails;
        std::printf("    query: info = %ld, work[0] = %g (expected 0, >= 1)\n",
                    (long)info, (double)wq);
    }
    std::vector<T> work((size_t)std::max<MKL_INT>((MKL_INT)wq, 1));
    compat<T>::orgqr(lay, m, n, k, ap, ld, taup, work.data(), (MKL_INT)work.size(), &info,
                     fmt, nm);
    if (info != 0) {
        ++fails;
        std::printf("    info = %ld (expected 0)\n", (long)info);
    }

    auto Qp = Qc.base_ptrs();
    mkl<T>::geunpack(lay, m, n, Qp.data(), ld, ap, ld, fmt, nm);

    double worst_el = 0, worst_orth = 0, worst_rec = 0;
    std::vector<T> Rs((size_t)kf * kf), Recs((size_t)m * kf);
    const auto R = mat_view(Rs.data(), kf, kf);
    const auto Rec = mat_view(Recs.data(), m, kf);
    for (int v = 0; v < nm; ++v) {
        const auto Q = Qc.view(v, rowmajor); /* the unpacked result, this layout */
        const auto Qref = Qd.view(v);

        /* elementwise vs LAPACKE_?orgqr */
        for (int j = 0; j < n; ++j)
            for (int i = 0; i < m; ++i)
                worst_el = std::max(worst_el, (double)std::abs(Q(i, j) - Qref(i, j)));

        /* orthogonality Q^T Q - I */
        worst_orth = std::max(worst_orth, orth_error(Q));

        /* reconstruction Q(:, 0:k-1) R = A0, R = triu of the factorization */
        if (k > 0) {
            for (int j = 0; j < k; ++j)
                for (int i = 0; i < k; ++i)
                    R(i, j) = (i <= j) ? Hk(v, i, j) : T(0);
            matmul(leading(Qc.view(v, rowmajor), m, k), leading(R, k, k),
                   leading(Rec, m, k));
            /* Recs and A0[v] are both contiguous column-major m x k here */
            worst_rec =
                std::max(worst_rec, max_abs_diff(Recs.data(), A0[v], (size_t)m * k) /
                                        std::max(norm1(A0.view(v)), norm_floor));
        }
    }

    const double tol_el = cross_tol<T>();
    const double tol_orth = 100.0 * n * eps, tol_rec = 100.0 * m * eps;
    bool ok = (worst_el <= tol_el) && (worst_orth <= tol_orth) && (worst_rec <= tol_rec);
    fails += !ok;
    std::printf("  [suite1] %s V=%-2d nm=%-2d m=%-3d n=%-3d k=%-3d | el %.2e (%.0e) orth "
                "%.2e (%.1e) rec %.2e (%.1e) %s\n",
                rowmajor ? "row" : "col", V, nm, m, n, k, worst_el, tol_el, worst_orth,
                tol_orth, worst_rec, tol_rec, ok ? "OK" : "FAIL");
    return fails;
}

/* ------- Suite 2: vs cbk_?ormqr_compact on a packed identity ------- */

template <class T> int suite2(int nm, int m, int k)
{
    const double eps = std::numeric_limits<T>::epsilon();
    const MKL_COMPACT_PACK fmt = mkl_get_format_compact();
    const int V = mkl<T>::vlen(fmt);

    /* dense factorization -> (H, tau), packed twice (orgqr overwrites) */
    MatrixBatch<T> A0(nm, m, k), Hk(nm, m, k), tau(nm, k, 1), I(nm, m, k);
    for (int v = 0; v < nm; ++v) {
        gen_boosted(A0.view(v));
        std::copy(A0[v], A0[v] + A0.stride(), Hk[v]);
        lapack<T>::geqrf(LAPACK_COL_MAJOR, m, k, Hk[v], m, tau[v]);
        const auto Iv = I.view(v);
        for (int j = 0; j < k; ++j)
            for (int i = 0; i < m; ++i)
                Iv(i, j) = (i == j) ? T(1) : T(0);
    }

    MKL_INT sz_a = mkl<T>::get_size(m, k, fmt, nm);
    MKL_INT sz_t = mkl<T>::get_size(k, 1, fmt, nm);
    auto hp_buf = cbk::detail::mkl_alloc_bytes<T>(sz_a); /* pristine reflectors */
    auto qp_buf = cbk::detail::mkl_alloc_bytes<T>(sz_a); /* orgqr, in place */
    auto cp_buf = cbk::detail::mkl_alloc_bytes<T>(sz_a); /* ormqr on identity */
    auto tp_buf = cbk::detail::mkl_alloc_bytes<T>(sz_t);
    T *hp = hp_buf.get(), *qp = qp_buf.get(), *cp = cp_buf.get(), *taup = tp_buf.get();
    auto Hp = Hk.base_ptrs();
    auto Tp = tau.base_ptrs();
    auto Ip = I.base_ptrs();
    mkl<T>::gepack(MKL_COL_MAJOR, m, k, Hp.data(), m, hp, m, fmt, nm);
    mkl<T>::gepack(MKL_COL_MAJOR, m, k, Hp.data(), m, qp, m, fmt, nm);
    mkl<T>::gepack(MKL_COL_MAJOR, m, k, Ip.data(), m, cp, m, fmt, nm);
    mkl<T>::gepack(MKL_COL_MAJOR, k, 1, Tp.data(), k, taup, k, fmt, nm);

    int fails = 0;
    MKL_INT info = 99;

    /* route 1: Q in place over the reflectors */
    T wq;
    compat<T>::orgqr(MKL_COL_MAJOR, m, k, k, qp, m, taup, &wq, -1, &info, fmt, nm);
    compat<T>::orgqr(MKL_COL_MAJOR, m, k, k, qp, m, taup, &wq, (MKL_INT)wq, &info, fmt,
                     nm);
    if (info != 0) {
        ++fails;
        std::printf("    orgqr info = %ld (expected 0)\n", (long)info);
    }

    /* route 2: Q I through the apply-Q sweep, with its own queried workspace */
    T wq2;
    compat<T>::ormqr(MKL_COL_MAJOR, 'L', 'N', m, k, k, hp, m, taup, cp, m, &wq2, -1,
                     &info, fmt, nm);
    compat<T>::ormqr(MKL_COL_MAJOR, 'L', 'N', m, k, k, hp, m, taup, cp, m, &wq2,
                     (MKL_INT)wq2, &info, fmt, nm);
    if (info != 0) {
        ++fails;
        std::printf("    ormqr info = %ld (expected 0)\n", (long)info);
    }

    /* the two compact buffers, padded lanes included, must agree */
    double d = max_abs_diff(qp, cp, (size_t)sz_a / sizeof(T));
    const double tol = 10.0 * eps;
    bool ok = (d <= tol);
    fails += !ok;
    std::printf("  [suite2] V=%-2d nm=%-2d m=%-3d k=%-3d | max|orgqr-ormqr(I)| %.2e "
                "(tol %.0e) %s\n",
                V, nm, m, k, d, tol, ok ? "OK" : "FAIL");
    return fails;
}

} /* anonymous namespace */

template <class T> int run_suites()
{
    std::printf("\n== %s: MKL compact format = %d, V = %d ==\n", compact<T>::name,
                (int)mkl_get_format_compact(), mkl<T>::vlen(mkl_get_format_compact()));

    int fails = 0;

    /* Suite 1: vs dense LAPACKE_?orgqr */
    fails += suite1<T>(8, 30, 30, 30);
    fails += suite1<T>(16, 60, 60, 60);
    fails += suite1<T>(11, 43, 43, 43); /* padded partial group */
    fails += suite1<T>(8, 64, 20, 20);  /* tall thin Q */
    fails += suite1<T>(8, 50, 24, 10);  /* k < n: unit-seeded extra columns */
    fails += suite1<T>(8, 128, 128, 128);
    fails += suite1<T>(8, 12, 8, 0);         /* k = 0: Q = leading columns of I */
    fails += suite1<T>(8, 30, 30, 30, true); /* row-major */
    fails += suite1<T>(11, 40, 24, 24, true);

    /* Suite 2: vs the apply-Q sweep on a packed identity */
    fails += suite2<T>(8, 30, 30);
    fails += suite2<T>(11, 43, 43); /* padded partial group */
    fails += suite2<T>(8, 64, 20);

    return fails;
}

int main()
{
    const int fails = run_suites<double>() + run_suites<float>();
    return finish(fails);
}
